<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>CalculadoraRealRacional</title>
    <link rel="stylesheet" type="text/css" href="estilo.css" media="screen" />
</head>


<body>
<div>
    <header>Calculadora de numeros reales y racionales</header>
    <fieldset>
        <legend>Establece la operación</legend>
        <form action='.' method="post">
            <div>
                <label for="operacion">Operación</label>
                <input type="text" name="operacion" id="operacion">
            </div>
            <button type="submit" id="calcular">Calcular</button>
        </form>
        <?php if (!empty($_POST)) {
            if ($procesamiento['ok']) {
                echo $operando1_nice . $procesamiento['operador'] . $operando2_nice . ' = ' . $resultado;
            } else {
                echo "La operación {$_POST['operacion']} no es correcta";
            }
        }?>
    </fieldset>
</div>

<div>
    <?php if (!empty($_POST) && $procesamiento['ok']): ?>
        <fieldset id="rtdo">
            <legend>Resultado</legend>
            <label>
                <table border="1">
                    <tbody>
                        <tr>
                            <th>Concepto</th>
                            <th>Valores</th>
                        </tr>
                        <tr>
                            <th>Operando 1</th>
                            <th><?=$operando1_nice?></th>
                        </tr>
                        <tr>
                            <th>Operando 2</th>
                            <th><?=$operando2_nice?></th>
                        </tr>
                        <tr>
                            <th>Operación</th>
                            <th><?=$procesamiento['operador']?></th>
                        </tr>
                        <tr>
                            <th>Tipo de operacion</th>
                            <th><?=ucfirst($procesamiento['tipo'])?></th>
                        </tr>
                        <tr>
                            <th>Resultado</th>
                            <th><?=$resultado?></th>
                        </tr>
                    </tbody>
                </table>
            </label>
        </fieldset>
    <?php endif; ?>
</div>

</body>

</html>